---
- hosts: local
  roles:
    - role: brew
      tags: [brew]
    - role: git
      tags: [git]
    - role: nodejs
      tags: [nodejs]
    - role: kitty
      tags: [kitty]
    - role: lazyvim
      tags: [lazyvim]
    - role: ai-agents
      tags: [ai-agents]
